--
-- PostgreSQL database dump
--

\restrict J4SORjdfnDDcc4YvnVdRtqtme6WYwZdYcV6txdMv3RRjS9GjGdZC1bZqpt1r08V

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointment (
    id bigint NOT NULL,
    date_time timestamp(6) without time zone NOT NULL,
    location character varying(255) NOT NULL,
    creator_id bigint NOT NULL
);


ALTER TABLE public.appointment OWNER TO postgres;

--
-- Name: appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: friend_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.friend_request (
    id bigint NOT NULL,
    status character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    CONSTRAINT friend_request_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.friend_request OWNER TO postgres;

--
-- Name: friend_request_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.friend_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friend_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.location (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    name character varying(255) NOT NULL,
    rating double precision NOT NULL,
    type character varying(255) NOT NULL,
    warning text
);


ALTER TABLE public.location OWNER TO postgres;

--
-- Name: location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    is_read boolean NOT NULL,
    message character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY ((ARRAY['FRIEND_REQUEST'::character varying, 'NEW_APPOINTMENT'::character varying])::text[])))
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: app_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_user (id, email, username) FROM stdin;
\.


--
-- Data for Name: appointment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointment (id, date_time, location, creator_id) FROM stdin;
\.


--
-- Data for Name: friend_request; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.friend_request (id, status, "timestamp", receiver_id, sender_id) FROM stdin;
\.


--
-- Data for Name: location; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.location (id, address, latitude, longitude, name, rating, type, warning) FROM stdin;
1	Via del Corso, 1, Roma	41.902782	12.496366	FitHub Central Gym	4.8	gym	\N
2	Piazza del Colosseo, 1, Roma	41.8986	12.5083	Colosseum Fitness	4.5	gym	Lat Machine broken
3	Piazza della Rotonda, Roma	41.907	12.475	Pantheon Gym & Spa	4.9	gym	\N
4	Via della Lungaretta, Roma	41.889	12.471	Trastevere CrossFit	4.6	gym	\N
5	Via Galvani, Roma	41.8765	12.478	Testaccio Boxing Club	4.7	gym	Dips Bar broken
6	Via Cola di Rienzo, Roma	41.9065	12.4565	Prati Fitness Center	4.4	gym	\N
7	Via Cavour, Roma	41.8955	12.501	Esquilino Gym	4.3	gym	\N
8	Via dei Serpenti, Roma	41.8945	12.492	Monti Strength Studio	4.8	gym	\N
9	Via Marsala, Roma	41.901	12.5025	Termini Wellness	4.2	gym	Pull-up bar needs maintenance
10	Piazza Campo de Fiori, Roma	41.8954	12.4724	Campo de Fiori Gym	4.5	gym	\N
11	Piazzale Napoleone I, Roma	41.9109	12.4818	Villa Borghese Park	4.7	park	\N
12	Piazza di Santa Maria, Roma	41.8929	12.4825	Trastevere Workout Park	4.3	park	\N
13	Via di Santa Sabina, Roma	41.885	12.488	Aventine Hill Park	4.6	park	Running track under repair
14	Via Aurelia Antica, Roma	41.885	12.45	Villa Pamphili	4.8	park	\N
15	Via Salaria, Roma	41.9325	12.5	Villa Ada Park	4.7	park	\N
16	Via Lemonia, Roma	41.855	12.545	Parco degli Acquedotti	4.9	park	\N
17	Viale del Monte Oppio, Roma	41.8925	12.4975	Colle Oppio Park	4.4	park	\N
18	Via della Caffarella, Roma	41.855	12.515	Parco della Caffarella	4.6	park	\N
19	Via Nomentana, Roma	41.915	12.508	Villa Torlonia	4.5	park	\N
20	Piazzale del Partigiano, Roma	41.928	12.475	Parco di Villa Glori	4.4	park	\N
21	Via del Corso, 1, Roma	41.902782	12.496366	FitHub Central Gym	4.8	gym	\N
22	Piazza del Colosseo, 1, Roma	41.8986	12.5083	Colosseum Fitness	4.5	gym	Lat Machine broken
23	Piazza della Rotonda, Roma	41.907	12.475	Pantheon Gym & Spa	4.9	gym	\N
24	Via della Lungaretta, Roma	41.889	12.471	Trastevere CrossFit	4.6	gym	\N
25	Via Galvani, Roma	41.8765	12.478	Testaccio Boxing Club	4.7	gym	Dips Bar broken
26	Via Cola di Rienzo, Roma	41.9065	12.4565	Prati Fitness Center	4.4	gym	\N
27	Via Cavour, Roma	41.8955	12.501	Esquilino Gym	4.3	gym	\N
28	Via dei Serpenti, Roma	41.8945	12.492	Monti Strength Studio	4.8	gym	\N
29	Via Marsala, Roma	41.901	12.5025	Termini Wellness	4.2	gym	Pull-up bar needs maintenance
30	Piazza Campo de Fiori, Roma	41.8954	12.4724	Campo de Fiori Gym	4.5	gym	\N
31	Piazzale Napoleone I, Roma	41.9109	12.4818	Villa Borghese Park	4.7	park	\N
32	Piazza di Santa Maria, Roma	41.8929	12.4825	Trastevere Workout Park	4.3	park	\N
33	Via di Santa Sabina, Roma	41.885	12.488	Aventine Hill Park	4.6	park	Running track under repair
34	Via Aurelia Antica, Roma	41.885	12.45	Villa Pamphili	4.8	park	\N
35	Via Salaria, Roma	41.9325	12.5	Villa Ada Park	4.7	park	\N
36	Via Lemonia, Roma	41.855	12.545	Parco degli Acquedotti	4.9	park	\N
37	Viale del Monte Oppio, Roma	41.8925	12.4975	Colle Oppio Park	4.4	park	\N
38	Via della Caffarella, Roma	41.855	12.515	Parco della Caffarella	4.6	park	\N
39	Via Nomentana, Roma	41.915	12.508	Villa Torlonia	4.5	park	\N
40	Piazzale del Partigiano, Roma	41.928	12.475	Parco di Villa Glori	4.4	park	\N
41	Via del Corso, 1, Roma	41.902782	12.496366	FitHub Central Gym	4.8	gym	\N
42	Piazza del Colosseo, 1, Roma	41.8986	12.5083	Colosseum Fitness	4.5	gym	Lat Machine broken
43	Piazza della Rotonda, Roma	41.907	12.475	Pantheon Gym & Spa	4.9	gym	\N
44	Via della Lungaretta, Roma	41.889	12.471	Trastevere CrossFit	4.6	gym	\N
45	Via Galvani, Roma	41.8765	12.478	Testaccio Boxing Club	4.7	gym	Dips Bar broken
46	Via Cola di Rienzo, Roma	41.9065	12.4565	Prati Fitness Center	4.4	gym	\N
47	Via Cavour, Roma	41.8955	12.501	Esquilino Gym	4.3	gym	\N
48	Via dei Serpenti, Roma	41.8945	12.492	Monti Strength Studio	4.8	gym	\N
49	Via Marsala, Roma	41.901	12.5025	Termini Wellness	4.2	gym	Pull-up bar needs maintenance
50	Piazza Campo de Fiori, Roma	41.8954	12.4724	Campo de Fiori Gym	4.5	gym	\N
51	Piazzale Napoleone I, Roma	41.9109	12.4818	Villa Borghese Park	4.7	park	\N
52	Piazza di Santa Maria, Roma	41.8929	12.4825	Trastevere Workout Park	4.3	park	\N
53	Via di Santa Sabina, Roma	41.885	12.488	Aventine Hill Park	4.6	park	Running track under repair
54	Via Aurelia Antica, Roma	41.885	12.45	Villa Pamphili	4.8	park	\N
55	Via Salaria, Roma	41.9325	12.5	Villa Ada Park	4.7	park	\N
56	Via Lemonia, Roma	41.855	12.545	Parco degli Acquedotti	4.9	park	\N
57	Viale del Monte Oppio, Roma	41.8925	12.4975	Colle Oppio Park	4.4	park	\N
58	Via della Caffarella, Roma	41.855	12.515	Parco della Caffarella	4.6	park	\N
59	Via Nomentana, Roma	41.915	12.508	Villa Torlonia	4.5	park	\N
60	Piazzale del Partigiano, Roma	41.928	12.475	Parco di Villa Glori	4.4	park	\N
\.


--
-- Data for Name: notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notification (id, is_read, message, "timestamp", type, user_id) FROM stdin;
\.


--
-- Name: app_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_user_id_seq', 6, true);


--
-- Name: appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointment_id_seq', 2, true);


--
-- Name: friend_request_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.friend_request_id_seq', 4, true);


--
-- Name: location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.location_id_seq', 60, true);


--
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notification_id_seq', 5, true);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: appointment appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT appointment_pkey PRIMARY KEY (id);


--
-- Name: friend_request friend_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friend_request
    ADD CONSTRAINT friend_request_pkey PRIMARY KEY (id);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: app_user uk1j9d9a06i600gd43uu3km82jw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);


--
-- Name: app_user uk3k4cplvh82srueuttfkwnylq0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk3k4cplvh82srueuttfkwnylq0 UNIQUE (username);


--
-- Name: idx_appointment_creator; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_appointment_creator ON public.appointment USING btree (creator_id);


--
-- Name: idx_appointment_datetime; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_appointment_datetime ON public.appointment USING btree (date_time DESC);


--
-- Name: idx_friend_request_receiver; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_friend_request_receiver ON public.friend_request USING btree (receiver_id);


--
-- Name: idx_friend_request_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_friend_request_status ON public.friend_request USING btree (status);


--
-- Name: idx_friend_request_users; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_friend_request_users ON public.friend_request USING btree (sender_id, receiver_id);


--
-- Name: idx_location_coords; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_location_coords ON public.location USING btree (latitude, longitude);


--
-- Name: idx_location_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_location_type ON public.location USING btree (type);


--
-- Name: idx_notification_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notification_timestamp ON public.notification USING btree ("timestamp" DESC);


--
-- Name: idx_notification_user_read; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notification_user_read ON public.notification USING btree (user_id, is_read);


--
-- Name: appointment fk1s05dlq76s430rox96aotbxvm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT fk1s05dlq76s430rox96aotbxvm FOREIGN KEY (creator_id) REFERENCES public.app_user(id);


--
-- Name: notification fkcxbqr6g1py0j4m9qeq44h1ju6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkcxbqr6g1py0j4m9qeq44h1ju6 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: friend_request fkjl1eidcaf3wm4m1331raprtq4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friend_request
    ADD CONSTRAINT fkjl1eidcaf3wm4m1331raprtq4 FOREIGN KEY (receiver_id) REFERENCES public.app_user(id);


--
-- Name: friend_request fkr01bk66rn5812qvn2grh24urr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friend_request
    ADD CONSTRAINT fkr01bk66rn5812qvn2grh24urr FOREIGN KEY (sender_id) REFERENCES public.app_user(id);


--
-- PostgreSQL database dump complete
--

\unrestrict J4SORjdfnDDcc4YvnVdRtqtme6WYwZdYcV6txdMv3RRjS9GjGdZC1bZqpt1r08V

