--
-- PostgreSQL database dump
--

\restrict UPLdwRh4cM7tP9BI1IVcFQCrsQqVMIrFxNk3WEi47qVVQ2abi6lKwgQB0skc66V

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255),
    is_public boolean DEFAULT false,
    current_streak integer DEFAULT 0,
    weekly_workouts_done integer DEFAULT 0,
    week_start_date date,
    last_workout_date date,
    is_admin boolean DEFAULT false NOT NULL,
    status_message text
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointment (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(100),
    location character varying(255),
    date_time timestamp without time zone NOT NULL,
    creator_id bigint NOT NULL
);


ALTER TABLE public.appointment OWNER TO postgres;

--
-- Name: appointment_confirmation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointment_confirmation (
    id bigint NOT NULL,
    appointment_id bigint NOT NULL,
    user_id bigint NOT NULL,
    confirmed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.appointment_confirmation OWNER TO postgres;

--
-- Name: appointment_confirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.appointment_confirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.appointment_confirmation_id_seq OWNER TO postgres;

--
-- Name: appointment_confirmation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.appointment_confirmation_id_seq OWNED BY public.appointment_confirmation.id;


--
-- Name: appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.appointment_id_seq OWNER TO postgres;

--
-- Name: appointment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.appointment_id_seq OWNED BY public.appointment.id;


--
-- Name: blacklist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blacklist (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    email character varying(255) NOT NULL,
    reason text,
    banned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    banned_by bigint
);


ALTER TABLE public.blacklist OWNER TO postgres;

--
-- Name: blacklist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.blacklist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.blacklist_id_seq OWNER TO postgres;

--
-- Name: blacklist_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.blacklist_id_seq OWNED BY public.blacklist.id;


--
-- Name: exercise_preset; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercise_preset (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    muscle_group character varying(120),
    equipment character varying(120),
    path character varying(255)
);


ALTER TABLE public.exercise_preset OWNER TO postgres;

--
-- Name: exercise_preset_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.exercise_preset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.exercise_preset_id_seq OWNER TO postgres;

--
-- Name: exercise_preset_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.exercise_preset_id_seq OWNED BY public.exercise_preset.id;


--
-- Name: friend_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.friend_request (
    id bigint NOT NULL,
    status character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    CONSTRAINT friend_request_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('ACCEPTED'::character varying)::text, ('REJECTED'::character varying)::text])))
);


ALTER TABLE public.friend_request OWNER TO postgres;

--
-- Name: friend_request_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.friend_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friend_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.location (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    warning text
);


ALTER TABLE public.location OWNER TO postgres;

--
-- Name: location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meal_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meal_items (
    id bigint NOT NULL,
    meal_id bigint NOT NULL,
    food_name character varying(255) NOT NULL,
    image_url text,
    grams integer NOT NULL,
    calories integer NOT NULL,
    proteins double precision NOT NULL,
    carbs double precision NOT NULL,
    fats double precision NOT NULL
);


ALTER TABLE public.meal_items OWNER TO postgres;

--
-- Name: meal_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.meal_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.meal_items_id_seq OWNER TO postgres;

--
-- Name: meal_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.meal_items_id_seq OWNED BY public.meal_items.id;


--
-- Name: meals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meals (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    total_calories integer DEFAULT 0,
    date_eaten timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.meals OWNER TO postgres;

--
-- Name: meals_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.meals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.meals_id_seq OWNER TO postgres;

--
-- Name: meals_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.meals_id_seq OWNED BY public.meals.id;


--
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    is_read boolean NOT NULL,
    message character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY (ARRAY[('FRIEND_REQUEST'::character varying)::text, ('NEW_APPOINTMENT'::character varying)::text])))
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workout_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_item (
    id bigint NOT NULL,
    exercise_id bigint NOT NULL,
    "position" integer NOT NULL,
    sets integer NOT NULL,
    reps integer NOT NULL,
    note text,
    plan_id bigint NOT NULL,
    day_of_week character varying(16) NOT NULL
);


ALTER TABLE public.workout_item OWNER TO postgres;

--
-- Name: workout_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.workout_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.workout_item_id_seq OWNER TO postgres;

--
-- Name: workout_item_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.workout_item_id_seq OWNED BY public.workout_item.id;


--
-- Name: workout_plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_plan (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    title character varying(255) DEFAULT 'Scheda'::character varying
);


ALTER TABLE public.workout_plan OWNER TO postgres;

--
-- Name: workout_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.workout_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.workout_plan_id_seq OWNER TO postgres;

--
-- Name: workout_plan_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.workout_plan_id_seq OWNED BY public.workout_plan.id;


--
-- Name: appointment id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment ALTER COLUMN id SET DEFAULT nextval('public.appointment_id_seq'::regclass);


--
-- Name: appointment_confirmation id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment_confirmation ALTER COLUMN id SET DEFAULT nextval('public.appointment_confirmation_id_seq'::regclass);


--
-- Name: blacklist id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blacklist ALTER COLUMN id SET DEFAULT nextval('public.blacklist_id_seq'::regclass);


--
-- Name: exercise_preset id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_preset ALTER COLUMN id SET DEFAULT nextval('public.exercise_preset_id_seq'::regclass);


--
-- Name: meal_items id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meal_items ALTER COLUMN id SET DEFAULT nextval('public.meal_items_id_seq'::regclass);


--
-- Name: meals id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meals ALTER COLUMN id SET DEFAULT nextval('public.meals_id_seq'::regclass);


--
-- Name: workout_item id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_item ALTER COLUMN id SET DEFAULT nextval('public.workout_item_id_seq'::regclass);


--
-- Name: workout_plan id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_plan ALTER COLUMN id SET DEFAULT nextval('public.workout_plan_id_seq'::regclass);


--
-- Data for Name: app_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_user (id, email, username, password, is_public, current_streak, weekly_workouts_done, week_start_date, last_workout_date, is_admin, status_message) FROM stdin;
1	test@gmail.com	ale c	$2a$10$6FqlkZ1qlfotYz9HzMRpUONoms7xJ/.DdYunHvh561BNjBM1X7yka	f	0	0	\N	\N	t	\N
2	alessandro@fithub.it	alessandro curcio	$2a$10$sp/1lXmzf.R8Z2Q/HeVcSeSVfaG7zEybmvTg6U036/WJYovlRBE3y	f	0	0	\N	\N	t	\N
3	antonio@fithub.it	antonio dambrosio	$2a$10$gjdu33ZtQlt0P3tirunGq.oIMsxQl.eJUwvGOPC6XBjRe/b88suwu	f	0	0	\N	\N	f	\N
5	simone@fithub.it	simone leone	$2a$10$aW/YH1.EN7ZW3jXUr783b.PrJLbgBgiIBHUe31zrygSfvEOvPyMFm	f	0	0	\N	\N	f	\N
4	irene@fithub.it	irene covelli	$2a$10$uTytXejqLHPIQe1eZTu6Z.1aXLbhS4zHDBiqOvrXvXJGFlMYMYjb.	f	0	0	\N	\N	f	l'allenamento e' la mia vita!
\.


--
-- Data for Name: appointment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointment (id, title, type, location, date_time, creator_id) FROM stdin;
1	allenamento greve	HIIT	31B	2026-01-19 10:00:00	3
\.


--
-- Data for Name: appointment_confirmation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointment_confirmation (id, appointment_id, user_id, confirmed_at) FROM stdin;
1	1	2	2026-01-16 18:29:31.533797
\.


--
-- Data for Name: blacklist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.blacklist (id, user_id, email, reason, banned_at, banned_by) FROM stdin;
1	5	simone@fithub.it	BANana	2026-01-16 18:15:35.431391	2
\.


--
-- Data for Name: exercise_preset; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exercise_preset (id, name, muscle_group, equipment, path) FROM stdin;
17	Calf raises	Polpacci	Corpo libero	assets/exercises/calf-raises.png
13	Croci manubri	Petto	Manubri	assets/exercises/croci-manubri.png
20	Crunch	Addominali	Corpo libero	assets/exercises/crunch.png
5	Curl manubri	Bicipiti	Manubri	assets/exercises/curl-manubri.png
11	Dips	Tricipiti	Parallele	assets/exercises/dips.png
16	French press	Tricipiti	Bilanciere	assets/exercises/french-press.png
4	Lat machine	Dorsali	Macchina	assets/exercises/lat-machine.png
18	Leg curl	Femorali	Macchina	assets/exercises/leg-curl.png
19	Leg extension	Quadricipiti	Macchina	assets/exercises/leg-extension.png
7	Leg press	Gambe	Macchina	assets/exercises/leg-press.png
6	Military press	Spalle	Bilanciere	assets/exercises/military-press.png
1	Panca piana	Petto	Bilanciere	assets/exercises/panca-piana.png
8	Plank	Core	Corpo libero	assets/exercises/plank.png
10	Pull up	Dorsali	Sbarra	assets/exercises/pull-ups.png
9	Push up	Petto	Corpo libero	assets/exercises/push-ups.png
14	Rematore	Dorsali	Bilanciere	assets/exercises/rematore.png
2	Squat	Gambe	Bilanciere	assets/exercises/squat.png
3	Stacco da terra	Schiena	Bilanciere	assets/exercises/stacco-da-terra.png
12	Affondi	Gambe	Corpo libero	../../../assets/exercises/affondi.png
15	Alzate laterali	Spalle	Manubri	../assets/exercises/alzate-laterali.png
\.


--
-- Data for Name: friend_request; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.friend_request (id, status, "timestamp", receiver_id, sender_id) FROM stdin;
3	ACCEPTED	2026-01-16 16:49:28.931966	1	1
4	ACCEPTED	2026-01-16 18:22:52.240981	3	2
\.


--
-- Data for Name: location; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.location (id, address, latitude, longitude, name, type, warning) FROM stdin;
4	Via della Lungaretta, Roma	41.889	12.471	Trastevere CrossFit	gym	\N
5	Via Galvani, Roma	41.8765	12.478	Testaccio Boxing Club	gym	Dips Bar broken
7	Via Cavour, Roma	41.8955	12.501	Esquilino Gym	gym	\N
8	Via dei Serpenti, Roma	41.8945	12.492	Monti Strength Studio	gym	\N
9	Via Marsala, Roma	41.901	12.5025	Termini Wellness	gym	Pull-up bar needs maintenance
10	Piazza Campo de Fiori, Roma	41.8954	12.4724	Campo de Fiori Gym	gym	\N
12	Piazza di Santa Maria, Roma	41.8929	12.4825	Trastevere Workout Park	park	\N
13	Via di Santa Sabina, Roma	41.885	12.488	Aventine Hill Park	park	Running track under repair
14	Via Aurelia Antica, Roma	41.885	12.45	Villa Pamphili	park	\N
15	Via Salaria, Roma	41.9325	12.5	Villa Ada Park	park	\N
16	Via Lemonia, Roma	41.855	12.545	Parco degli Acquedotti	park	\N
17	Viale del Monte Oppio, Roma	41.8925	12.4975	Colle Oppio Park	park	\N
18	Via della Caffarella, Roma	41.855	12.515	Parco della Caffarella	park	\N
19	Via Nomentana, Roma	41.915	12.508	Villa Torlonia	park	\N
20	Piazzale del Partigiano, Roma	41.928	12.475	Parco di Villa Glori	park	\N
21	Via del Corso, 1, Roma	41.902782	12.496366	FitHub Central Gym	gym	\N
22	Piazza del Colosseo, 1, Roma	41.8986	12.5083	Colosseum Fitness	gym	Lat Machine broken
26	Via Cola di Rienzo, Roma	41.9065	12.4565	Prati Fitness Center	gym	\N
1	via vittorio alfieri	39.34022633910285	16.24637603759766	prince	gym	\N
2	via londra	39.3429064227757	16.239713430404667	parchetto dei criminali	park	\N
3	via giuseppe verdi	39.34435428900188	16.244557499885563	gierre fitness club	gym	\N
4	via antonio dambrosio	39.355878068635434	16.239093840122226	elite fitness club	gym	\N
5	via esame web application	39.3633936351311	16.226117312908176	31B	gym	\N
\.


--
-- Data for Name: meal_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.meal_items (id, meal_id, food_name, image_url, grams, calories, proteins, carbs, fats) FROM stdin;
1	1	Nutella	https://images.openfoodfacts.org/images/products/301/762/042/5035/front_en.583.400.jpg	1000	5390	63	575	309
2	2	Spaghetti Senza Glutine	https://images.openfoodfacts.org/images/products/807/680/954/5440/front_en.245.400.jpg	100	358	7	79	2
\.


--
-- Data for Name: meals; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.meals (id, user_id, name, total_calories, date_eaten) FROM stdin;
1	4	pre-workout fit!	5390	2026-01-16 18:44:54.419216
2	4	Pranzo del campione	358	2026-01-16 18:50:13.148466
\.


--
-- Data for Name: notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notification (id, is_read, message, "timestamp", type, user_id) FROM stdin;
2	t	ale c has sent you a friend request.	2026-01-16 16:48:47.109628	FRIEND_REQUEST	1
3	t	ale c has sent you a friend request.	2026-01-16 16:49:28.989619	FRIEND_REQUEST	1
1	t	ale c has sent you a friend request.	2026-01-16 16:48:46.95125	FRIEND_REQUEST	1
4	t	alessandro curcio has sent you a friend request.	2026-01-16 18:22:52.283719	FRIEND_REQUEST	3
5	f	antonio dambrosio ha creato un nuovo appuntamento: allenamento greve	2026-01-16 18:28:13.826792	NEW_APPOINTMENT	2
6	f	alessandro curcio ha confermato la partecipazione a: allenamento greve	2026-01-16 18:29:31.689852	NEW_APPOINTMENT	3
\.


--
-- Data for Name: workout_item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_item (id, exercise_id, "position", sets, reps, note, plan_id, day_of_week) FROM stdin;
1	15	0	3	10		1	MONDAY
2	17	1	3	10		1	MONDAY
3	11	0	3	10		2	MONDAY
4	16	1	3	10		2	MONDAY
5	6	2	3	10		2	MONDAY
6	1	3	3	10		2	MONDAY
7	2	0	3	10		2	WEDNESDAY
8	18	1	3	10		2	WEDNESDAY
9	19	2	3	10		2	WEDNESDAY
10	7	3	3	10		2	WEDNESDAY
11	8	0	3	10		2	FRIDAY
12	14	1	3	10		2	FRIDAY
13	3	2	3	10		2	FRIDAY
14	12	0	3	10		3	MONDAY
15	17	1	3	10		3	MONDAY
16	13	2	3	10		3	MONDAY
\.


--
-- Data for Name: workout_plan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_plan (id, user_id, start_date, end_date, created_at, title) FROM stdin;
2	1	2026-01-16	2026-01-16	2026-01-16 16:58:17.865144	massa
3	1	2026-01-16	2026-02-20	2026-01-16 16:59:30.177172	prova
\.


--
-- Name: app_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_user_id_seq', 5, true);


--
-- Name: appointment_confirmation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointment_confirmation_id_seq', 1, true);


--
-- Name: appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointment_id_seq', 1, true);


--
-- Name: blacklist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.blacklist_id_seq', 1, true);


--
-- Name: exercise_preset_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exercise_preset_id_seq', 1, false);


--
-- Name: friend_request_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.friend_request_id_seq', 4, true);


--
-- Name: location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.location_id_seq', 5, true);


--
-- Name: meal_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.meal_items_id_seq', 2, true);


--
-- Name: meals_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.meals_id_seq', 2, true);


--
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notification_id_seq', 6, true);


--
-- Name: workout_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workout_item_id_seq', 16, true);


--
-- Name: workout_plan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workout_plan_id_seq', 3, true);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: meal_items meal_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meal_items
    ADD CONSTRAINT meal_items_pkey PRIMARY KEY (id);


--
-- Name: meals meals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meals
    ADD CONSTRAINT meals_pkey PRIMARY KEY (id);


--
-- Name: idx_meal_items_meal; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meal_items_meal ON public.meal_items USING btree (meal_id);


--
-- Name: idx_meals_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meals_date ON public.meals USING btree (date_eaten DESC);


--
-- Name: idx_meals_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meals_user ON public.meals USING btree (user_id);


--
-- Name: meal_items meal_items_meal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meal_items
    ADD CONSTRAINT meal_items_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meals(id) ON DELETE CASCADE;


--
-- Name: meals meals_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meals
    ADD CONSTRAINT meals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict UPLdwRh4cM7tP9BI1IVcFQCrsQqVMIrFxNk3WEi47qVVQ2abi6lKwgQB0skc66V

