--
-- PostgreSQL database dump
--

\restrict wVBmce96FKnGdq5BrqinlSRLTszoe07mPWM307Ygn7eQSmeGfcJX8vuDLlSQNCc

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255)
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointment (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(100),
    location character varying(255),
    date_time timestamp without time zone NOT NULL,
    creator_id bigint NOT NULL
);


ALTER TABLE public.appointment OWNER TO postgres;

--
-- Name: appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.appointment_id_seq OWNER TO postgres;

--
-- Name: appointment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.appointment_id_seq OWNED BY public.appointment.id;


--
-- Name: exercise_preset; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercise_preset (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    muscle_group character varying(120),
    equipment character varying(120),
    path character varying(255)
);


ALTER TABLE public.exercise_preset OWNER TO postgres;

--
-- Name: exercise_preset_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.exercise_preset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.exercise_preset_id_seq OWNER TO postgres;

--
-- Name: exercise_preset_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.exercise_preset_id_seq OWNED BY public.exercise_preset.id;


--
-- Name: friend_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.friend_request (
    id bigint NOT NULL,
    status character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    CONSTRAINT friend_request_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('ACCEPTED'::character varying)::text, ('REJECTED'::character varying)::text])))
);


ALTER TABLE public.friend_request OWNER TO postgres;

--
-- Name: friend_request_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.friend_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friend_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.location (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    name character varying(255) NOT NULL,
    rating double precision NOT NULL,
    type character varying(255) NOT NULL,
    warning text
);


ALTER TABLE public.location OWNER TO postgres;

--
-- Name: location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    is_read boolean NOT NULL,
    message character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY (ARRAY[('FRIEND_REQUEST'::character varying)::text, ('NEW_APPOINTMENT'::character varying)::text])))
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workout_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_item (
    id bigint NOT NULL,
    exercise_id bigint NOT NULL,
    "position" integer NOT NULL,
    sets integer NOT NULL,
    reps integer NOT NULL,
    note text,
    plan_id bigint NOT NULL,
    day_of_week character varying(16) NOT NULL
);


ALTER TABLE public.workout_item OWNER TO postgres;

--
-- Name: workout_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.workout_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.workout_item_id_seq OWNER TO postgres;

--
-- Name: workout_item_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.workout_item_id_seq OWNED BY public.workout_item.id;


--
-- Name: workout_plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_plan (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    title character varying(255) DEFAULT 'Scheda'::character varying
);


ALTER TABLE public.workout_plan OWNER TO postgres;

--
-- Name: workout_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.workout_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.workout_plan_id_seq OWNER TO postgres;

--
-- Name: workout_plan_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.workout_plan_id_seq OWNED BY public.workout_plan.id;


--
-- Name: appointment id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment ALTER COLUMN id SET DEFAULT nextval('public.appointment_id_seq'::regclass);


--
-- Name: exercise_preset id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_preset ALTER COLUMN id SET DEFAULT nextval('public.exercise_preset_id_seq'::regclass);


--
-- Name: workout_item id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_item ALTER COLUMN id SET DEFAULT nextval('public.workout_item_id_seq'::regclass);


--
-- Name: workout_plan id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_plan ALTER COLUMN id SET DEFAULT nextval('public.workout_plan_id_seq'::regclass);


--
-- Data for Name: app_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_user (id, email, username, password) FROM stdin;

\.


--
-- Data for Name: appointment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointment (id, title, type, location, date_time, creator_id) FROM stdin;
\.


--
-- Data for Name: exercise_preset; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.exercise_preset ("name",muscle_group,equipment,"path") VALUES
	 ('Calf raises','Polpacci','Corpo libero','assets/exercises/calf-raises.png'),
	 ('Croci manubri','Petto','Manubri','assets/exercises/croci-manubri.png'),
	 ('Crunch','Addominali','Corpo libero','assets/exercises/crunch.png'),
	 ('Curl manubri','Bicipiti','Manubri','assets/exercises/curl-manubri.png'),
	 ('Dips','Tricipiti','Parallele','assets/exercises/dips.png'),
	 ('French press','Tricipiti','Bilanciere','assets/exercises/french-press.png'),
	 ('Lat machine','Dorsali','Macchina','assets/exercises/lat-machine.png'),
	 ('Leg curl','Femorali','Macchina','assets/exercises/leg-curl.png'),
	 ('Leg extension','Quadricipiti','Macchina','assets/exercises/leg-extension.png'),
	 ('Leg press','Gambe','Macchina','assets/exercises/leg-press.png');
INSERT INTO public.exercise_preset ("name",muscle_group,equipment,"path") VALUES
	 ('Military press','Spalle','Bilanciere','assets/exercises/military-press.png'),
	 ('Panca piana','Petto','Bilanciere','assets/exercises/panca-piana.png'),
	 ('Plank','Core','Corpo libero','assets/exercises/plank.png'),
	 ('Pull up','Dorsali','Sbarra','assets/exercises/pull-ups.png'),
	 ('Push up','Petto','Corpo libero','assets/exercises/push-ups.png'),
	 ('Rematore','Dorsali','Bilanciere','assets/exercises/rematore.png'),
	 ('Squat','Gambe','Bilanciere','assets/exercises/squat.png'),
	 ('Stacco da terra','Schiena','Bilanciere','assets/exercises/stacco-da-terra.png'),
	 ('Affondi','Gambe','Corpo libero','../../../assets/exercises/affondi.png'),
	 ('Alzate laterali','Spalle','Manubri','../assets/exercises/alzate-laterali.png');


--
-- Data for Name: friend_request; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.friend_request (id, status, "timestamp", receiver_id, sender_id) FROM stdin;
\.


--
-- Data for Name: location; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.location (id, address, latitude, longitude, name, rating, type, warning) FROM stdin;

\.


--
-- Data for Name: notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notification (id, is_read, message, "timestamp", type, user_id) FROM stdin;
\.


--
-- Data for Name: workout_item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_item (id, exercise_id, "position", sets, reps, note, plan_id, day_of_week) FROM stdin;

\.


--
-- Data for Name: workout_plan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_plan (id, user_id, start_date, end_date, created_at, title) FROM stdin;
\.



--
-- Name: app_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_user_id_seq', 11, true);


--
-- Name: appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointment_id_seq', 1, false);


--
-- Name: exercise_preset_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exercise_preset_id_seq', 20, true);


--
-- Name: friend_request_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.friend_request_id_seq', 4, true);


--
-- Name: location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.location_id_seq', 60, true);


--
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notification_id_seq', 5, true);


--
-- Name: workout_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workout_item_id_seq', 43, true);


--
-- Name: workout_plan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workout_plan_id_seq', 27, true);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: appointment appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT appointment_pkey PRIMARY KEY (id);


--
-- Name: exercise_preset exercise_preset_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_preset
    ADD CONSTRAINT exercise_preset_pkey PRIMARY KEY (id);


--
-- Name: friend_request friend_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friend_request
    ADD CONSTRAINT friend_request_pkey PRIMARY KEY (id);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: app_user uk1j9d9a06i600gd43uu3km82jw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);


--
-- Name: app_user uk3k4cplvh82srueuttfkwnylq0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk3k4cplvh82srueuttfkwnylq0 UNIQUE (username);


--
-- Name: workout_item workout_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_item
    ADD CONSTRAINT workout_item_pkey PRIMARY KEY (id);


--
-- Name: workout_plan workout_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_plan
    ADD CONSTRAINT workout_plan_pkey PRIMARY KEY (id);


--
-- Name: idx_friend_request_receiver; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_friend_request_receiver ON public.friend_request USING btree (receiver_id);


--
-- Name: idx_friend_request_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_friend_request_status ON public.friend_request USING btree (status);


--
-- Name: idx_friend_request_users; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_friend_request_users ON public.friend_request USING btree (sender_id, receiver_id);


--
-- Name: idx_location_coords; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_location_coords ON public.location USING btree (latitude, longitude);


--
-- Name: idx_location_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_location_type ON public.location USING btree (type);


--
-- Name: idx_notification_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notification_timestamp ON public.notification USING btree ("timestamp" DESC);


--
-- Name: idx_notification_user_read; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notification_user_read ON public.notification USING btree (user_id, is_read);


--
-- Name: idx_workout_item_plan_day; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_workout_item_plan_day ON public.workout_item USING btree (plan_id, day_of_week);


--
-- Name: idx_workout_plan_user_dates; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_workout_plan_user_dates ON public.workout_plan USING btree (user_id, start_date, end_date);


--
-- Name: appointment fk_appointment_creator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT fk_appointment_creator FOREIGN KEY (creator_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- Name: notification fkcxbqr6g1py0j4m9qeq44h1ju6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkcxbqr6g1py0j4m9qeq44h1ju6 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: friend_request fkjl1eidcaf3wm4m1331raprtq4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friend_request
    ADD CONSTRAINT fkjl1eidcaf3wm4m1331raprtq4 FOREIGN KEY (receiver_id) REFERENCES public.app_user(id);


--
-- Name: friend_request fkr01bk66rn5812qvn2grh24urr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friend_request
    ADD CONSTRAINT fkr01bk66rn5812qvn2grh24urr FOREIGN KEY (sender_id) REFERENCES public.app_user(id);


--
-- Name: workout_item workout_item_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_item
    ADD CONSTRAINT workout_item_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercise_preset(id);


--
-- Name: workout_item workout_item_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_item
    ADD CONSTRAINT workout_item_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.workout_plan(id) ON DELETE CASCADE;


--
-- Name: workout_plan workout_plan_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_plan
    ADD CONSTRAINT workout_plan_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict wVBmce96FKnGdq5BrqinlSRLTszoe07mPWM307Ygn7eQSmeGfcJX8vuDLlSQNCc

